networks:
  app-network:
services:
  webserver:
    container_name: Fanmedia-PHP-webserver
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    networks:
      - app-network